# Generated by Django 2.1.7 on 2019-03-18 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumeSpider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posbrief',
            fields=[
                ('businessArea', models.CharField(max_length=100, verbose_name='公司位置')),
                ('createDate', models.DateTimeField(verbose_name='创建日期')),
                ('jobName', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('positionURL', models.URLField(primary_key=True, serialize=False, verbose_name='地址链接')),
                ('salary', models.CharField(max_length=30, verbose_name='薪资')),
                ('updateDate', models.DateTimeField(verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '职位简介表',
                'verbose_name_plural': '职位简介表',
                'db_table': 'Posbrief',
            },
        ),
        migrations.AddField(
            model_name='positions',
            name='pos_url',
            field=models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to='resumeSpider.Posbrief'),
            preserve_default=False,
        ),
    ]
