# Generated by Django 2.1.7 on 2019-03-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeSpider', '0002_auto_20190318_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='posbrief',
            name='company',
            field=models.CharField(default='', max_length=300, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='posbrief',
            name='companyLogo',
            field=models.CharField(default='', max_length=150, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='posbrief',
            name='eduLevel',
            field=models.CharField(default='', max_length=50, verbose_name='学历'),
        ),
        migrations.AddField(
            model_name='posbrief',
            name='jobTag',
            field=models.CharField(default='', max_length=100, verbose_name='工作福利'),
        ),
        migrations.AddField(
            model_name='posbrief',
            name='jobType',
            field=models.CharField(default='', max_length=100, verbose_name='工作类型'),
        ),
    ]
