# Generated by Django 2.1.7 on 2019-03-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeSpider', '0003_auto_20190319_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posbrief',
            name='company',
            field=models.CharField(default='', max_length=500, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='posbrief',
            name='jobType',
            field=models.CharField(default='', max_length=300, verbose_name='工作类型'),
        ),
    ]
