# Generated by Django 2.1.7 on 2019-03-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aboutme',
            field=models.CharField(max_length=300, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=50, null=True, verbose_name='住址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_time',
            field=models.DateField(null=True, verbose_name='出生年月'),
        ),
    ]
