# Generated by Django 2.1.7 on 2019-03-10 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190310_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Honor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hon_name', models.CharField(max_length=30, verbose_name='证书名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '荣誉证书表',
                'verbose_name_plural': '荣誉证书表',
                'db_table': 'Honor',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=30, verbose_name='项目名称')),
                ('pro_environment', models.CharField(max_length=30, verbose_name='项目环境')),
                ('pro_brief', models.CharField(max_length=300, verbose_name='项目介绍')),
                ('pro_photo', models.ImageField(default='', upload_to='images/resume', verbose_name='图片')),
                ('pro_responsibility', models.CharField(max_length=200, verbose_name='项目职责')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '项目经验表',
                'verbose_name_plural': '项目经验表',
                'db_table': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sillinfo', models.TextField(verbose_name='专业技能')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '专业技能表',
                'verbose_name_plural': '专业技能表',
                'db_table': 'Skill',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('worktime', models.CharField(max_length=30, verbose_name='工作时间')),
                ('company', models.CharField(max_length=30, verbose_name='公司')),
                ('position', models.CharField(max_length=30, verbose_name='职位')),
                ('responsibility', models.CharField(max_length=100, verbose_name='职责')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '工作经历表',
                'verbose_name_plural': '工作经历表',
                'db_table': 'WorkExperience',
            },
        ),
    ]
