# Generated by Django 2.1.7 on 2019-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20190312_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_name', models.CharField(max_length=30, verbose_name='姓名')),
                ('con_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('con_number', models.CharField(max_length=30, verbose_name='手机号码')),
                ('con_message', models.TextField(verbose_name='留言信息')),
                ('con_time', models.DateTimeField(verbose_name='留言时间')),
            ],
            options={
                'verbose_name': '留言表',
                'verbose_name_plural': '留言表',
                'db_table': 'Contact',
            },
        ),
    ]
