# Generated by Django 2.1.7 on 2019-03-13 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='sillinfo',
            new_name='skillinfo',
        ),
    ]
